### ISSUE TITLE
Separate name from card

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#1]
<img width="1440" alt="Screenshot 2023-10-06 at 10 41 07 AM" src="https://github.com/ContriHUB/Jodi-Makers/assets/79766263/61443cac-0a8d-4d33-9a77-00514f514d8e">

At present, target user's name is displayed on the top of the card which looks untidy. :(
Separate name from card such that the UI looks cool and attractive.

**Comment by Arghya-Banerjee** [comment]
Please assign me this issue

**Comment by Shivansh-243** [comment]
Sir I am requesting to assign it to me but it show 
![Screenshot_2023-10-12-16-24-15-76_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ContriHUB/Jodi-Makers/assets/125989942/4c6a4e55-71f3-4d2b-950d-9bdad242f5b3)
Why it is showing that
