### ISSUE TITLE
Change postion of logout button

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#10]
<img width="1440" alt="Screenshot 2023-10-06 at 12 04 29 PM" src="https://github.com/ContriHUB/Jodi-Makers/assets/79766263/5c1b9a23-3565-4468-ad9b-39a613be6b93">

Change location of logout button from the left sidebar to the top right corner of the page.

**Comment by aecuto** [comment]
assign me plz

**Comment by nitish-0211** [comment]
I'd like to contribute, please assign this issue to me

**Comment by Arcturus22** [comment]
@admirerr 
Please assign me this issue. I want to contribute.

**Comment by Ayushman444** [comment]
Hello Sir @admirerr , Please assign this issue to me ! I want to work on it.

**Comment by sudipa27** [comment]
Hello sir @admirerr, Please assign the issue to me!

**Comment by kumarharshh** [comment]
Hello @admirerr, I would like to contribute to this  as, I've looked into the codebase and identified that this change would primarily involve modifications. I'm confident that with a few tweaks, we can achieve this seamlessly. Can you please assign it to me?

**Comment by Khanak21** [comment]
<img width="690" alt="image" src="https://github.com/ContriHUB/Jodi-Makers/assets/127039986/30601ef8-4245-4f03-8012-0028692a37d8">
Sir mongodb is giving this error,it's not getting connected. I'm not being able to log in

**Comment by Khanak21** [comment]
Sir mongodb got connected,but then still when I click on submit I can't view the homepage
