### ISSUE TITLE
Change current bar color

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#12]
<img width="1440" alt="Screenshot 2023-10-06 at 12 07 31 PM" src="https://github.com/ContriHUB/Jodi-Makers/assets/79766263/d5ee0949-6ccd-48d6-9ccb-049455197a78">
Color of the chat bar fades away when we click on the matches but color of matches bar does not fade away when we click on chat.
<img width="1440" alt="Screenshot 2023-10-06 at 12 13 20 PM" src="https://github.com/ContriHUB/Jodi-Makers/assets/79766263/5824c812-0a8a-41f9-890d-316ad6bd1c6d">

You are required to make necessary changes so that color of matches bar also fades away once a chat of particular match is opened.

**Comment by Arcturus22** [comment]
Please assign me this issue.
@admirerr

**Comment by RKOsvk** [comment]
Can I start work on this issue? Can you assign me?

**Comment by RSGPhoeniX01** [comment]
please assign me this issue ?

**Comment by Madhurgupta12** [comment]
Please assign me this issue

**Comment by Ayushman444** [comment]
Hello Sir @admirerr , Please assign this issue to me ! I want to work on it.

**Comment by Codipk** [comment]
Hello sir ,Can you assign this issue to me @admirerr
