### ISSUE TITLE
Improve the appearance of sidebar

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#13]
Sidebar in the dashboard page seems to be blank :(
Improve the look and appearance of the sidebar so that the dashboard page becomes cool and attractive.

**Comment by yashrajoria03** [comment]
can i work on this issue?

**Comment by RKOsvk** [comment]
Can I start work on this issue? Can you assign me?

**Comment by ujjwal13818** [comment]
Please assign this issue to me, I can make it more attractive.
