### ISSUE TITLE
Add option to upload photo

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#2]
<img width="1440" alt="Screenshot 2023-10-06 at 10 55 06 AM" src="https://github.com/ContriHUB/Jodi-Makers/assets/79766263/f07e5bb7-f5bf-4818-a307-8650945b7571">

We are now required to provide active online link for the profile picture while creating a new account. Make necessary modifications so that we may have the option to upload photo from our local computer while creating a new account.

**Comment by tejjusbhat** [comment]
can I be assigned this issue?

**Comment by RKOsvk** [comment]
Can I start work on this issue? Can you assign me?

**Comment by Codipk** [comment]
Hello sir, Can you assign this issue to me @admirerr

**Comment by lokesh-wagh** [comment]
Can you assign me this issue if no one is working on it

**Comment by Sahilgupta3224** [comment]
please reject my request for this one
