### ISSUE TITLE
Add contraints to the password

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#3]
Add necessary constraints to the password while creating a new account in order to make it more secure.

**Comment by Panth1823** [comment]
can u assign this issue to me ? @admirerr

**Comment by meenakshi3151** [comment]
Sir can you assign this issue to me? @admirerr

**Comment by Ayushman444** [comment]
Hello Sir @admirerr , Please assign this issue to me ! I want to work on it.

**Comment by shank03** [comment]
Completed
