### ISSUE TITLE
Make account creation atomic

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#4]
Currently, if you leave the account creation process in the intermediate stage and quit (register your email id and password but don't submit other profile related details). Now at this stage if you want to login using your credentials, a blank page will be displayed as the account creation process was incomplete :(

Make necessary modification so that the account creation process becomes atomic i.e. - if the account details are not submitted completely, intermediate details (email id and password) must not be stored in the database.

**Comment by lokesh-wagh** [comment]
Are we supposed to use cookies for this one

**Comment by lokesh-wagh** [comment]
How about we save the incomplete details in cookies and redirect the user to complete the registration from where he left
