### ISSUE TITLE
Change the name in the logo

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#5]
Throughout all the pages wherever you find the name `tinder` replace it with the name `Jodi-Makers`.

**Comment by aecuto** [comment]
assign me plz

**Comment by Arcturus22** [comment]
Please assign me this issue.
@admirerr

**Comment by Madhav-495** [comment]
@admirerr  assign it to me

**Comment by Ayushman444** [comment]
Hello Sir @admirerr , Please assign this issue to me ! I want to work on it.

**Comment by echohint1** [comment]
hello sir, I am very much intrested in this task i wanna work on this project so pls assign this to me.

**Comment by kumarharshh** [comment]
Hello, I want to work on this task so it would be really helpful if you assign this task to me

**Comment by kumarharshh** [comment]
Hello, I want to work on this task so it would be really helpful if you assign this task to me
