### ISSUE TITLE
Add calendar for selection of date of birth

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#6]
<img width="1440" alt="Screenshot 2023-10-06 at 11 24 21 AM copy" src="https://github.com/ContriHUB/Jodi-Makers/assets/79766263/4bb97a85-e294-4772-8e0e-255824abc62a">

While creating a new account, now one is required to type his/her date of birth manually. Embed option to add date of birth through `calendar GUI` and provide necessary constraints for it.

**Comment by insane-22** [comment]
Hey @admirerr ! I would like to contribute to your project under hacktoberfest 2023, could you please assign the issue to me?
Thank you for your consideration

**Comment by Vyshu2** [comment]
!ASSIGN

**Comment by Madhurgupta12** [comment]
Assign me this issue

**Comment by Ayushman444** [comment]
Hello Sir @admirerr , Please assign this issue to me ! I want to work on it.

**Comment by admirerr** [comment]
Solved
