### ISSUE TITLE
Add Google Auth

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#7]
Provide the option for SignIn/SignUp through Google Auth. User must land on to a new page where he must be required to fill additional details which is necessary for the account creation.

**Comment by mangalgithub** [comment]
Can you assign this issue to me.

**Comment by lokesh-wagh** [comment]
Hey !!
I want to work on this issue 

I can use passport js to perform the google authentication

**Comment by Sahilgupta3224** [comment]
Hey!
I wanna work on this issue.
please assign this to me.
