### ISSUE TITLE
Add glassmorphism effect

### ISSUE THREAD

**Issue by admirerr** [ContriHUB/Jodi-Makers#9]
<img width="1440" alt="Screenshot 2023-10-06 at 11 41 41 AM" src="https://github.com/ContriHUB/Jodi-Makers/assets/79766263/88ea85c7-f54f-4748-b228-785125978bf9">

SignIn and Create account tile looks dull. Add glassmorphism effect to it so that it may look attractive and enhance beauty of the page :)

**Comment by shreyanshig** [comment]
Hi @admirerr, please assign this to me

**Comment by mangalgithub** [comment]
Hi @admirerr, can you assign this issue to me.

**Comment by Khanak21** [comment]
Hi @admirerr can you assign me this issue?

**Comment by admirerr** [comment]
@Khanak21 raise a request from the official site of Contrihub

**Comment by admirerr** [comment]
> Hi @admirerr can you assign me this issue?

@Khanak21 raise a request from the official site of Contrihub
